successMessage: Priority class has been set
failureMessage: Priority class should be set
category: Reliability
target: PodSpec
schema:
  "$schema": "http://json-schema.org/draft/2019-09/schema"
  type: object
  required:
  - priorityClassName
mutations:
  - op: add
    path: /priorityClassName
    value: high-priority